# conda_recipe/meta.yaml

package:
  name: online_form_filling
  version: "0.1.0"

source:
  path: ..

build:
  script: python -m pip install .
  environment:
    file: environment.yaml

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pip
    
test:
  commands:
    - pytest

about:
  home: https://github.com/OzMaatuk/OnlineFormFilling
  license: MIT
  summary: "A project for automating online form filling using Playwright and LLMs."